a=int(input("Enter first integer:"))
b=int(input("Entee the second integer:"))
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("floor division:",a//b)
print("Modulus:",a%b)
print("Exponentiation:",a**b)
